window.env = {
  "TERM_PROGRAM": "vscode",
  "rvm_bin_path": "/Users/din/.rvm/bin",
  "TERM": "xterm-256color",
  "SHELL": "/bin/bash",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TMPDIR": "/var/folders/sg/w1tt8p891214hb9hzqwpf93r0000gn/T/",
  "TERM_PROGRAM_VERSION": "1.52.0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "COLOR": "1",
  "TERM_SESSION_ID": "47BEA8D7-DD7D-4BE6-8D9A-D50485981120",
  "USER": "din",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "rvm_path": "/Users/din/.rvm",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.89uxrCSK7V/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "rvm_prefix": "/Users/din",
  "npm_config_init.module": "/Users/din/.npm-init.js",
  "PATH": "/Users/din/Desktop/Front-end-Projects/music-player/node_modules/.bin:/Users/din/Desktop/Front-end-Projects/node_modules/.bin:/Users/din/Desktop/node_modules/.bin:/Users/din/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/opt/ruby/bin:/Users/din/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/opt/ruby/bin:/Users/din/.rbenv/shims:/Users/din/flutter/.pub-cache/bin:/Users/din/flutter/bin:/Users/din/.rvm/bin:/Users/din/flutter/.pub-cache/bin:/Users/din/flutter/bin",
  "npm_package_json": "/Users/din/Desktop/Front-end-Projects/music-player/package.json",
  "_": "/Users/din/Desktop/Front-end-Projects/music-player/node_modules/.bin/react-dotenv",
  "npm_config_userconfig": "/Users/din/.npmrc",
  "npm_config_init_module": "/Users/din/.npm-init.js",
  "npm_command": "start",
  "PWD": "/Users/din/Desktop/Front-end-Projects/music-player",
  "npm_lifecycle_event": "start",
  "EDITOR": "vi",
  "npm_package_name": "music-player",
  "LANG": "en_US.UTF-8",
  "XPC_FLAGS": "0x0",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "RBENV_SHELL": "bash",
  "npm_package_version": "0.1.0",
  "XPC_SERVICE_NAME": "0",
  "rvm_version": "1.29.10 (latest)",
  "HOME": "/Users/din",
  "SHLVL": "4",
  "APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL": "true",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "npm_config_cache": "/Users/din/.npm",
  "LOGNAME": "din",
  "npm_lifecycle_script": "react-dotenv && npm-run-all build:tailwind --parallel watch:tailwind start:react",
  "PREFIX": "/usr/local",
  "LC_CTYPE": "UTF-8",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/sg/w1tt8p891214hb9hzqwpf93r0000gn/T/vscode-git-8957d5688b.sock",
  "npm_config_user_agent": "npm/7.0.10 node/v15.2.1 darwin x64",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)",
  "npm_node_execpath": "/usr/local/Cellar/node/15.2.1/bin/node",
  "npm_config_prefix": "/usr/local",
  "COLORTERM": "truecolor",
  "CLIENT_ID": "d90419c92a394294aa09182c83bd03ab"
};